version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  allow:
  - dependency-type: direct
  - dependency-type: indirect
